# ------------------------------------------------
# author: @github.com/akashchouhan16
# ------------------------------------------------

name: Node.js CI - Unit Tests

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "publish" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, latest]
        express-version: [latest, next]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test